// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cloud_logic : 'enable',
aws_cloud_logic_custom : '[{"id":"rnxer16hr4","name":"Pets","description":"","endpoint":"https://rnxer16hr4.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}]',
aws_cognito_identity_pool_id : 'us-east-1:8d8619d6-fd14-4eed-9ecd-f0cee41894ff',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'reactnativestarter-hosting-mobilehub-1368366646',
aws_content_delivery_bucket_region : 'us-east-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd2rmdqsl7xxgsz.cloudfront.net',
aws_dynamodb : 'enable',
aws_dynamodb_all_tables_region : 'us-east-1',
aws_dynamodb_table_schemas : '[{"tableName":"reactnativestarter-mobilehub-1368366646-pets","attributes":[{"name":"userId","type":"S"},{"name":"petId","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"petId"}]',
aws_mobile_analytics_app_id : '70bee28d64304444b5384f9f4f26f160',
aws_project_id : 'c4269318-a798-4fe8-944f-72f2370e4cac',
aws_project_name : 'reactnative-starter',
aws_project_region : 'us-east-1',
aws_resource_bucket_name : 'reactnativestarter-deployments-mobilehub-1368366646',
aws_resource_name_prefix : 'reactnativestarter-mobilehub-1368366646',
aws_sign_in_enabled : 'enable',
aws_user_files : 'enable',
aws_user_files_s3_bucket : 'reactnativestarter-userfiles-mobilehub-1368366646',
aws_user_files_s3_bucket_region : 'us-east-1',
aws_user_pools : 'enable',
aws_user_pools_id : 'us-east-1_yDzIcgpv3',
aws_user_pools_mfa_type : 'ON',
aws_user_pools_web_client_id : '2tnb5re1niijg5dpjbgitum071',
aws_user_settings : 'enable',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});